/**
 * Regenerates src/components/Icon.data.ts from the Material Symbols SVG set.
 *
 * Icons are inlined as path data instead of loaded as an icon font: the font is
 * a ligature font, so a failed download would render the icon's English name
 * ("block", "visibility") as visible text — on a Hindi screen too. Inlining
 * also removes a render-blocking request on slow connections.
 *
 * Usage (only needed when ICONS below changes):
 *   npm install --no-save @material-symbols/svg-400
 *   node scripts/build-icons.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ICONS = [
  'accessibility',
  'air',
  'block',
  'bloodtype',
  'bolt',
  'call',
  'cardiology',
  'check',
  'coronavirus',
  'device_thermostat',
  'emergency',
  'falling',
  'info',
  'local_drink',
  'local_fire_department',
  'local_shipping',
  'medical_services',
  'mic',
  'neurology',
  'personal_injury',
  'pest_control',
  'pets',
  'photo_camera',
  'pool',
  'pregnant_woman',
  'psychology',
  'pulmonology',
  'search',
  'stop_circle',
  'sunny',
  'verified',
  'visibility',
  'water_drop',
];

const root = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(
  root,
  '..',
  'node_modules',
  '@material-symbols',
  'svg-400',
  'outlined',
);

const entries = [];
for (const name of ICONS) {
  const svg = await readFile(path.join(srcDir, `${name}.svg`), 'utf8');
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`no path data in ${name}.svg`);
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 -960 960 960';
  entries.push({ name, viewBox, d: paths.join(' ') });
}

const file = `// Generated by scripts/build-icons.mjs. Do not edit by hand.
// Source: @material-symbols/svg-400 (Apache-2.0), outlined weight 400.

export interface IconGlyph {
  viewBox: string;
  d: string;
}

export const ICON_GLYPHS = {
${entries
  .map((e) => `  ${e.name}: { viewBox: '${e.viewBox}', d: '${e.d}' },`)
  .join('\n')}
} as const satisfies Record<string, IconGlyph>;

export type IconName = keyof typeof ICON_GLYPHS;
`;

const out = path.join(root, '..', 'src', 'components', 'Icon.data.ts');
await writeFile(out, file, 'utf8');
console.log(`wrote ${entries.length} glyphs to ${path.relative(root, out)}`);
